language: node_js

node_js:
  - "11.2.0"

script:
  - node --version
  - npm install
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $ANGULAR_SELF_STUDY
  local-dir: dist/angular-self-study
  keep-history: true
  on:
    branch: master

git:
  depth: 10
